### ISSUE TITLE
Compatibilità dispositivi Armv7

### ISSUE THREAD

**Issue by Rufusnightly** [samuele-visentin/Flutter_MiruAnime#6]
L' app sembra funzionare solo su dispositivi armv8 se è possibile creare una versione armv7 o fare un apk universale per vari dispositivi android, grazie

**Comment by samuele-visentin** [comment]
Si effettivamente l'apk supporta solo armv8 per risparmiare spazio sull'installazione, però vedrò di caricare una versione che supporta tutto al costo di aumentare lo spazio di installazione di un po'.

**Comment by Rufusnightly** [comment]
Ottimo lavoro 👍 grazie
