### ISSUE TITLE
RangeError (length): Invalid value: Only valid value is 0:1

### ISSUE THREAD

**Issue by SilkierLyric146** [samuele-visentin/Flutter_MiruAnime#7]
Buonasera , da qualche giorno appena aperta l'app lo scraping non sembra più funzionare , l'errore riportato è questo :

RangeError (length): Invalid value: Only valid value is 0:1  (allego anche screnshot)

Il sito è online , non so se sia dovuto ad un cambio della struttura web di Animeworld o una loro recente modifica lato frontend , ma direi che è la cosa più probabile 
![Screenshot_2024-10-18-00-55-34-88_5fc73a5eb22d523eaf2e9de1a03ace88](https://github.com/user-attachments/assets/3b05845a-3c96-478f-9ce9-d686acd305c6)

Se gentilmente a tempo perso potete verificare.

Ps: app favolosa

**Comment by G4s01** [comment]
Si, per favore.
Senza guardare draghi masochisti che si trasformano in donnine non so come tirare avanti🙏🏻

**Comment by Kalsifer-742** [comment]
Skill Issue @SilkierLyric146 @Michele24102001 
The app is working fine for me

**Comment by samuele-visentin** [comment]
Ogni tanto può succedere che non va perche attivano una protezione al sito ma solo per poco tempo (almeno credo, è difficile testare perchè quando mi metto va sempre)
